spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hibernate_example?useSSL=false
    username: root
    password: Password123
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format-sql: true
        enable_lazy_load_no_trans: true
        event:
          merge:
            entity_copy_observer: allow
    hibernate:
      ddl-auto: update

server:
  port: 8081
