spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hibernate_example?useSSL=false
    username: root
    password: Password123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
